# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lgp <- function(x, z, lambda, nB, nT, n, J, tJ, nDmax, lJ, theta, d, mud, sigd, a, beta, eps, mud_prior_mean = 0.0, mud_prior_stdev = 10.0, sigd_prior_max = 2.0, lambdal_prior_min = 0.0, lambdal_prior_max = 2.0) {
    .Call(`_hlt_lgp`, x, z, lambda, nB, nT, n, J, tJ, nDmax, lJ, theta, d, mud, sigd, a, beta, eps, mud_prior_mean, mud_prior_stdev, sigd_prior_max, lambdal_prior_min, lambdal_prior_max)
}

abs2 <- function(x) {
    .Call(`_hlt_abs2`, x)
}

lt <- function(x, z, iter, burn, delta, post, ix, ixe, npar, n, nB, J, nDmax, lJ, nT, tJ, accept, eps, display_progress = TRUE) {
    .Call(`_hlt_lt`, x, z, iter, burn, delta, post, ix, ixe, npar, n, nB, J, nDmax, lJ, nT, tJ, accept, eps, display_progress)
}

